# Sample workflow for building and deploying a React site to GitHub Pages
name: Deploy React with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
        id: pages
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build with React
        run: npm run build:pages
        env:
          NODE_ENV: production
      - name: Verify build output
        run: |
          echo "Verifying build output..."
          ls -la dist/
          echo "Checking for required files..."
          test -f dist/index.html || (echo "Missing index.html" && exit 1)
          test -f dist/404.html || (echo "Missing 404.html" && exit 1)
          test -f dist/.nojekyll || (echo "Missing .nojekyll" && exit 1)
          echo "Checking assets directory..."
          test -d dist/assets || (echo "Missing assets directory" && exit 1)
          ls -la dist/assets/
          echo "Verifying HTML content..."
          grep -q "/ToolMaster/" dist/index.html || (echo "Base path not found in index.html" && exit 1)
          echo "Build verification complete!"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
